id: c246e1e523094e25993477f0e7b8a120
initial_creation_type: ocr
source_metadata:
  volumes:
    7389d8bff08d4802836f98beff736f8d:
      base_file: v034.txt
      image_group_id: I1PD95879
      title: ''
      total_pages: 1734
      volume_number: 34
